spring.application.name=geolab-system
spring.datasource.url=jdbc:postgresql://localhost:5432/geolab_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
server.port=8080
jwt.secret=jwt.secret=${JWT_SECRET:test9a4f2c8d3e1f0b5a6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b}
jwt.access-expiration=900000
jwt.refresh-expiration=604800000
spring.jpa.open-in-view=false
