CREATE TABLE daily_works
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    amount BIGINT NOT NULL,
    work_date DATE NOT NULL,
    notes VARCHAR(1000),
    work_day_id VARCHAR(1000),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_daily_works_order FOREIGN KEY (order_id) REFERENCES lab_orders(id) ON DELETE CASCADE
);