CREATE TABLE daily_works
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT    NOT NULL REFERENCES lab_orders(id),
    amount      INTEGER   NOT NULL CHECK (amount > 0),
    work_date   DATE      NOT NULL DEFAULT CURRENT_DATE,
    note        VARCHAR(500),
    created_at  TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_daily_works_order ON daily_works(order_id);
CREATE INDEX idx_daily_works_date  ON daily_works(work_date);