CREATE TABLE dispatches
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        BIGINT    NOT NULL REFERENCES lab_orders(id),
    amount          INTEGER   NOT NULL CHECK (amount > 0),
    dispatch_date   DATE      NOT NULL,
    note            VARCHAR(500),
    created_at      TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_dispatches_order  ON dispatches(order_id);
CREATE INDEX idx_dispatches_date   ON dispatches(dispatch_date);