CREATE TABLE dispatches
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      BIGINT    NOT NULL,
    amount        BIGINT    NOT NULL,
    dispatch_date DATE      NOT NULL,
    notes         VARCHAR(1000),
    sending_id    VARCHAR(1000),
    created_at    TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_dispatches_order FOREIGN KEY (order_id) REFERENCES lab_orders (id) ON DELETE CASCADE
);