CREATE TABLE lab_orders
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(50),
    geologist_name VARCHAR(50),
    amount INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(50),
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);