CREATE TABLE lab_orders
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_name     VARCHAR(50)  NOT NULL,
    description    VARCHAR(500) NOT NULL,
    geologist_name VARCHAR(500) NOT NULL,
    amount         BIGINT       NOT NULL DEFAULT 0,
    status         VARCHAR(20)  NOT NULL,
    created_at     TIMESTAMP    NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_order_object_geologist UNIQUE (order_name, description, geologist_name)
);