CREATE TABLE shipments
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    amount BIGINT NOT NULL,
    shipment_date DATE NOT NULL,
    notes VARCHAR(1000),
    shipping_id VARCHAR(1000),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_shipments_order FOREIGN KEY (order_id) REFERENCES lab_orders(id) ON DELETE CASCADE
);